# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/sia/Downloads/clion-2019.1.1/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/sia/Downloads/clion-2019.1.1/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sia/TIM_GED_Code

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sia/TIM_GED_Code

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/sia/Downloads/clion-2019.1.1/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/sia/Downloads/clion-2019.1.1/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sia/TIM_GED_Code/CMakeFiles /home/sia/TIM_GED_Code/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sia/TIM_GED_Code/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gaitEventDetect

# Build rule for target.
gaitEventDetect: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gaitEventDetect
.PHONY : gaitEventDetect

# fast build rule for target.
gaitEventDetect/fast:
	$(MAKE) -f CMakeFiles/gaitEventDetect.dir/build.make CMakeFiles/gaitEventDetect.dir/build
.PHONY : gaitEventDetect/fast

fsrReading.o: fsrReading.cpp.o

.PHONY : fsrReading.o

# target to build an object file
fsrReading.cpp.o:
	$(MAKE) -f CMakeFiles/gaitEventDetect.dir/build.make CMakeFiles/gaitEventDetect.dir/fsrReading.cpp.o
.PHONY : fsrReading.cpp.o

fsrReading.i: fsrReading.cpp.i

.PHONY : fsrReading.i

# target to preprocess a source file
fsrReading.cpp.i:
	$(MAKE) -f CMakeFiles/gaitEventDetect.dir/build.make CMakeFiles/gaitEventDetect.dir/fsrReading.cpp.i
.PHONY : fsrReading.cpp.i

fsrReading.s: fsrReading.cpp.s

.PHONY : fsrReading.s

# target to generate assembly for a file
fsrReading.cpp.s:
	$(MAKE) -f CMakeFiles/gaitEventDetect.dir/build.make CMakeFiles/gaitEventDetect.dir/fsrReading.cpp.s
.PHONY : fsrReading.cpp.s

logCreate.o: logCreate.cpp.o

.PHONY : logCreate.o

# target to build an object file
logCreate.cpp.o:
	$(MAKE) -f CMakeFiles/gaitEventDetect.dir/build.make CMakeFiles/gaitEventDetect.dir/logCreate.cpp.o
.PHONY : logCreate.cpp.o

logCreate.i: logCreate.cpp.i

.PHONY : logCreate.i

# target to preprocess a source file
logCreate.cpp.i:
	$(MAKE) -f CMakeFiles/gaitEventDetect.dir/build.make CMakeFiles/gaitEventDetect.dir/logCreate.cpp.i
.PHONY : logCreate.cpp.i

logCreate.s: logCreate.cpp.s

.PHONY : logCreate.s

# target to generate assembly for a file
logCreate.cpp.s:
	$(MAKE) -f CMakeFiles/gaitEventDetect.dir/build.make CMakeFiles/gaitEventDetect.dir/logCreate.cpp.s
.PHONY : logCreate.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/gaitEventDetect.dir/build.make CMakeFiles/gaitEventDetect.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/gaitEventDetect.dir/build.make CMakeFiles/gaitEventDetect.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/gaitEventDetect.dir/build.make CMakeFiles/gaitEventDetect.dir/main.cpp.s
.PHONY : main.cpp.s

signalInterrupt.o: signalInterrupt.cpp.o

.PHONY : signalInterrupt.o

# target to build an object file
signalInterrupt.cpp.o:
	$(MAKE) -f CMakeFiles/gaitEventDetect.dir/build.make CMakeFiles/gaitEventDetect.dir/signalInterrupt.cpp.o
.PHONY : signalInterrupt.cpp.o

signalInterrupt.i: signalInterrupt.cpp.i

.PHONY : signalInterrupt.i

# target to preprocess a source file
signalInterrupt.cpp.i:
	$(MAKE) -f CMakeFiles/gaitEventDetect.dir/build.make CMakeFiles/gaitEventDetect.dir/signalInterrupt.cpp.i
.PHONY : signalInterrupt.cpp.i

signalInterrupt.s: signalInterrupt.cpp.s

.PHONY : signalInterrupt.s

# target to generate assembly for a file
signalInterrupt.cpp.s:
	$(MAKE) -f CMakeFiles/gaitEventDetect.dir/build.make CMakeFiles/gaitEventDetect.dir/signalInterrupt.cpp.s
.PHONY : signalInterrupt.cpp.s

timeInterval.o: timeInterval.cpp.o

.PHONY : timeInterval.o

# target to build an object file
timeInterval.cpp.o:
	$(MAKE) -f CMakeFiles/gaitEventDetect.dir/build.make CMakeFiles/gaitEventDetect.dir/timeInterval.cpp.o
.PHONY : timeInterval.cpp.o

timeInterval.i: timeInterval.cpp.i

.PHONY : timeInterval.i

# target to preprocess a source file
timeInterval.cpp.i:
	$(MAKE) -f CMakeFiles/gaitEventDetect.dir/build.make CMakeFiles/gaitEventDetect.dir/timeInterval.cpp.i
.PHONY : timeInterval.cpp.i

timeInterval.s: timeInterval.cpp.s

.PHONY : timeInterval.s

# target to generate assembly for a file
timeInterval.cpp.s:
	$(MAKE) -f CMakeFiles/gaitEventDetect.dir/build.make CMakeFiles/gaitEventDetect.dir/timeInterval.cpp.s
.PHONY : timeInterval.cpp.s

xsensImu.o: xsensImu.cpp.o

.PHONY : xsensImu.o

# target to build an object file
xsensImu.cpp.o:
	$(MAKE) -f CMakeFiles/gaitEventDetect.dir/build.make CMakeFiles/gaitEventDetect.dir/xsensImu.cpp.o
.PHONY : xsensImu.cpp.o

xsensImu.i: xsensImu.cpp.i

.PHONY : xsensImu.i

# target to preprocess a source file
xsensImu.cpp.i:
	$(MAKE) -f CMakeFiles/gaitEventDetect.dir/build.make CMakeFiles/gaitEventDetect.dir/xsensImu.cpp.i
.PHONY : xsensImu.cpp.i

xsensImu.s: xsensImu.cpp.s

.PHONY : xsensImu.s

# target to generate assembly for a file
xsensImu.cpp.s:
	$(MAKE) -f CMakeFiles/gaitEventDetect.dir/build.make CMakeFiles/gaitEventDetect.dir/xsensImu.cpp.s
.PHONY : xsensImu.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... gaitEventDetect"
	@echo "... edit_cache"
	@echo "... fsrReading.o"
	@echo "... fsrReading.i"
	@echo "... fsrReading.s"
	@echo "... logCreate.o"
	@echo "... logCreate.i"
	@echo "... logCreate.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... signalInterrupt.o"
	@echo "... signalInterrupt.i"
	@echo "... signalInterrupt.s"
	@echo "... timeInterval.o"
	@echo "... timeInterval.i"
	@echo "... timeInterval.s"
	@echo "... xsensImu.o"
	@echo "... xsensImu.i"
	@echo "... xsensImu.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

